services:
  - type: web
    name: aco-analise-literaria
    runtime: python
    pythonVersion: "3.11"
    rootDir: aco-analise-literaria
    buildCommand: pip install -r fastapi_requirements.txt
    startCommand: uvicorn fastapi_main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALLOWED_ORIGIN
        value: "*"
